name: Mirroring

on: [push, delete]

jobs:
  to_bitbucket:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          git@bitbucket.org:patriciamedeiros/teste.git
        ssh_private_key:
          ${{ secrets.SSH_PRIVATE_KEY }}
