name: Mirroring
on: [ push, delete, create ]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:patmedeiros/teste2.git'
          destination-repo: 'git@bitbucket.org:patriciamedeiros/teste.git'
