name: Mirroring
on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "git@github.com:patmedeiros/teste2.git"
        source_branch: "master"
        destination_repo: "git@bitbucket.org:patriciamedeiros/teste.git"
        destination_branch: "master"
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
